services:
  - type: web
    name: zorvyn-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_PATH
        value: ./data/finance.db
      - key: PORT
        value: 10000

